In [2]:
import pandas as pd
import numpy as np

In [5]:
#dataframe with 3 columns/variables

data = pd.DataFrame({
    'X': np.array([20, 40, 60, 80]),
    'Y': np.array([60, 40, 22, 22]),
    'Z': np.array([6, 6, 2, 2])})

print(data)

    X   Y  Z
0  20  60  6
1  40  40  6
2  60  22  2
3  80  22  2


In [3]:
#obtain the matrix

mapping = {(x, y): z for (x, y, z) in data[["X", "Y", "Z"]].values}

n = len(data)
mat = np.zeros((n, n))

for i, x in np.ndenumerate(data["X"]):
    for j, y in np.ndenumerate(data["Y"]):
        mat[j, i] = mapping.get((x, y), 0)

        
print(mat)

[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 2. 2.]
 [0. 0. 2. 2.]]


# Following condition to populate the matrix further needs to be automated:

In [6]:
#Transform the matrix to the one below:
mat[1,0] = 6
mat[2,0] = 6
mat[3,0] = 6
mat[2,1] = 6
mat[3,1] = 6

print(mat)

[[6. 0. 0. 0.]
 [6. 6. 0. 0.]
 [6. 6. 2. 2.]
 [6. 6. 2. 2.]]


Condition that has been applied for above transformation:
For a given X, Z corresponding to the highest Y (in the column) is also the value for all lower Ys. 
For a given Y, Z corresponding to the highest X (in the row) is also the value in all lower Xs.

Final check of the matrix:
Higher Y should have lower or equal Z (for a given X). 
Higher X should have lower or equal Z (for a given Y). 

In [7]:
#Following transformation therefore is wrong and first transformation is right:
mat[2,0] = 2
mat[3,0] = 2
mat[2,1] = 2
mat[3,1] = 2

print(mat)

[[6. 0. 0. 0.]
 [6. 6. 0. 0.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
