In [2]:
import pandas as pd
import numpy as np

In [78]:
#dataframe with 3 columns/variables

data = pd.DataFrame({
    'X': np.round(np.random.rand(4)*100),
    'Y': np.round(np.random.rand(4)*100),
    'Z': np.round(np.random.rand(4)*10)})

#print(data)
data = data.sort_values('X', axis=0, ascending=True)
print(data)

#obtain the matrix
mapping = {(x, y): z for (x, y, z) in data[["X", "Y", "Z"]].values}

n = len(data)
mat = np.zeros((n, n))

for i, x in np.ndenumerate(data["X"]):
    for j, y in np.ndenumerate(data["Y"]):
        mat[j, i] = mapping.get((x, y), 0)

print(mat)

      X     Y    Z
3  61.0  48.0  6.0
1  72.0  94.0  9.0
2  88.0  20.0  4.0
0  96.0  29.0  8.0
[[6. 0. 0. 0.]
 [0. 9. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 8.]]


# Following condition to populate the matrix further needs to be automated:

In [79]:
r, c = np.tril_indices_from(mat)

# determine fillable slots
newr = np.array([],dtype=int)
newc = np.array([],dtype=int)
for ct in range(len(r)):
    if mat[r[ct],c[ct]] == 0 :
        newr = np.append(newr,r[ct])
        newc = np.append(newc,c[ct])
        
print(newr)
# First Cycle Based on Column
value = data[data['Y'] == max(data['Y'])]['Z']
for ct in range(len(newr)):
    
    mat[newr[ct],newc[ct]] = value

    
# Second Cycle Based on Rows
value = data[data['X'] == max(data['X'])]['Z']
chckmat = np.copy(mat)
for ct in range(len(newr)):
    chckmat[newr[ct],newc[ct]] = value

    
# Condition Check
if chckmat[0,0] < chckmat[-1,0]:
    finalmat = chckmat
else:
    finalmat = mat
    
print(mat)

[1 2 2 3 3 3]
[[6. 0. 0. 0.]
 [9. 9. 0. 0.]
 [9. 9. 4. 0.]
 [9. 9. 9. 8.]]


Condition that has been applied for above transformation:
For a given X, Z corresponding to the highest Y (in the column) is also the value for all lower Ys. 
For a given Y, Z corresponding to the highest X (in the row) is also the value in all lower Xs.

Final check of the matrix:
Higher Y should have lower or equal Z (for a given X). 
Higher X should have lower or equal Z (for a given Y). 

# Example 2

In [5]:
data = pd.DataFrame({'X': np.array([10, 20, 35]),
    'Y': np.array([22, 150, 22]),
    'Z': np.array([7, 6, 7])})

    
#print(data)
data = data.sort_values('X', axis=0, ascending=True)
#print(data)

#obtain the matrix
mapping = {(x, y): z for (x, y, z) in data[["X", "Y", "Z"]].values}

n = len(data)
mat = np.zeros((n, n))

for i, x in np.ndenumerate(data["X"]):
    for j, y in np.ndenumerate(data["Y"]):
        mat[j, i] = mapping.get((x, y), 0)

print(mat)
orgmat =np.copy(mat)

[[7. 0. 7.]
 [0. 6. 0.]
 [7. 0. 7.]]


###### Old way of determining the matrix . This DO NOT solve the peculiar case .

In [4]:
###### Original way of determining the matrix 

r, c = np.tril_indices_from(mat)

# determine fillable slots
newr = np.array([],dtype=int)
newc = np.array([],dtype=int)
for ct in range(len(r)):
    if mat[r[ct],c[ct]] == 0 :
        newr = np.append(newr,r[ct])
        newc = np.append(newc,c[ct])
        
        
# First Cycle Based on Column
value = data[data['Y'] == max(data['Y'])]['Z']
for ct in range(len(newr)):
    mat[newr[ct],newc[ct]] = value

    
# Second Cycle Based on Rows
value = data[data['X'] == max(data['X'])]['Z']
chckmat = np.copy(mat)
for ct in range(len(newr)):
    chckmat[newr[ct],newc[ct]] = value

    
# Condition Check
if chckmat[0,0] < chckmat[-1,0]:
    finalmat = chckmat
else:
    finalmat = mat
    
print(finalmat)

[[7. 0. 7.]
 [6. 6. 0.]
 [7. 6. 7.]]


###### New way of determining the matrix : 29 - June-2020 . This solves the peculiar case also.

In [6]:
mat=np.copy(orgmat)
r, c = np.tril_indices_from(mat)

# determine fillable slots
newr = np.array([],dtype=int)
newc = np.array([],dtype=int)
for i in range(np.size(mat,0)):
    for j in range(np.size(mat,1)):
        if mat[i,j] == 0 :
            newr = np.append(newr,i)
            newc = np.append(newc,j)
        
# First Cycle Based on Column
value = data[data['Y'] == max(data['Y'])]['Z']

for ct in range(len(newr)):
        mat[newr[ct],newc[ct]] = value      

# Modification
for i in range(0,np.size(mat,0)):
    for j in range(i+1,np.size(mat,1)):
        if orgmat[i,j] == 0:
            if mat[i,j] < max(orgmat[:,j]):
                mat[i,j] = orgmat[i,j]
    

# Second Cycle Based on Rows
value = data[data['X'] == max(data['X'])]['Z']
chckmat = np.copy(mat)
for ct in range(len(newr)):
        chckmat[newr[ct],newc[ct]] = value

    
# Condition Check
if chckmat[0,0] < chckmat[-1,0]:
    finalmat = chckmat
else:
    finalmat = mat
    
print(finalmat)

[[7. 6. 7.]
 [6. 6. 0.]
 [7. 6. 7.]]
