In [ ]:
import pandas as pd
import numpy as np

#dataframe with 3 columns/variables

data = pd.DataFrame({
    'X': np.round(np.random.rand(4)*100),
    'Y': np.round(np.random.rand(4)*100),
    'Z': np.round(np.random.rand(4)*10)})

#print(data)
data = data.sort_values('X', axis=0, ascending=True)
print(data)

#obtain the matrix
mapping = {(x, y): z for (x, y, z) in data[["X", "Y", "Z"]].values}

n = len(data)
mat = np.zeros((n, n))

for i, x in np.ndenumerate(data["X"]):
    for j, y in np.ndenumerate(data["Y"]):
        mat[j, i] = mapping.get((x, y), 0)

print(mat)

In [ ]:
r, c = np.tril_indices_from(mat)

# determine fillable slots
newr = np.array([],dtype=int)
newc = np.array([],dtype=int)
for ct in range(len(r)):
    if mat[r[ct],c[ct]] == 0 :
        newr = np.append(newr,r[ct])
        newc = np.append(newc,c[ct])
        
print(newr)
# First Cycle Based on Column
value = data[data['Y'] == max(data['Y'])]['Z']
for ct in range(len(newr)):
    
    mat[newr[ct],newc[ct]] = value

    
# Second Cycle Based on Rows
value = data[data['X'] == max(data['X'])]['Z']
chckmat = np.copy(mat)
for ct in range(len(newr)):
    chckmat[newr[ct],newc[ct]] = value

    
# Condition Check
if chckmat[0,0] < chckmat[-1,0]:
    finalmat = chckmat
else:
    finalmat = mat
    
print(mat)

Condition that has been applied for above transformation:
For a given X, Z corresponding to the highest Y (in the column) is also the value for all lower Ys. 
For a given Y, Z corresponding to the highest X (in the row) is also the value in all lower Xs.

Final check of the matrix:
Higher Y should have lower or equal Z (for a given X). 
Higher X should have lower or equal Z (for a given Y). 

# Example 2

In [1]:
import pandas as pd
import numpy as np

In [18]:
data = pd.DataFrame({'X': np.array([10, 20, 35]),
    'Y': np.array([22, 150, 22]),
    'Z': np.array([7, 6, 7])})

    
#print(data)
data = data.sort_values('X', axis=0, ascending=True)
#print(data)

#obtain the matrix
mapping = {(x, y): z for (x, y, z) in data[["X", "Y", "Z"]].values}

n = len(data)
mat = np.zeros((n, n))

for i, x in np.ndenumerate(data["X"]):
    for j, y in np.ndenumerate(data["Y"]):
        mat[j, i] = mapping.get((x, y), 0)

print(mat)

[[7. 0. 7.]
 [0. 6. 0.]
 [7. 0. 7.]]


In [19]:
orgmat = np.copy(mat)
r, c = np.tril_indices_from(mat)

# determine fillable slots
mr = np.size(mat, 0)
mc = np.size(mat, 1)

newr = np.array([], dtype = int)
newc = np.array([], dtype = int)
for i in range(mr):
    for j in range(mc):
        if mat[i,j] == 0:
            newr = np.append(newr,i)
            newc = np.append(newc,j)
        
#### First Cycle Based on Column
value = data[data['Y'] == max(data['Y'])]['Z']
for i in range(len(newr)):
    mat[newr[i], newc[i]] = value


for i in range(0, mr):
    for j in range(i+1, mc):
        if orgmat[i,j] == 0:
            if mat[i,j] < max(orgmat[:,j]):
                mat[i,j] = orgmat[i,j]

                
#### Second Cycle Based on Rows
value = data[data['X'] == max(data['X'])]['Z']
chckmat = np.copy(mat)
for i in range(len(newr)):
    chckmat[newr[i], newc[i]] = value

                
#### Condition Check
if chckmat[0,0] < chckmat[-1,0]:
    finalmat = chckmat
else:
    finalmat = mat
    
print(finalmat)

[[7. 6. 7.]
 [6. 6. 0.]
 [7. 6. 7.]]
